@baseUrl = https://limitless-atoll-37666.herokuapp.com

@JWTtoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTY0MjQ3ZDRkY2IyY2U4ODRmNTZiOWYiLCJlbWFpbCI6Ikphbm5lQGRvZS5jb20iLCJpYXQiOjE2MzQyOTYzNTAsImV4cCI6MTYzNDM4Mjc1MH0.hqWI0L3Xy_7HZ7hQAfEGKeAIQrn0mVgW1LRNcR9W54I
###
GET {{baseUrl}}


###

POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "Janne@doe.com",
    "password": "Password123"
}


###
GET {{baseUrl}}/cabins/owned
Content-Type: application/json
Authorization: Bearer {{JWTtoken}}