@remoteUrl = https://secret-shelf-13108.herokuapp.com

@localUrl = http://127.0.0.1:5000

@baseUrl = https://limitless-atoll-37666.herokuapp.com

GET  {{remoteUrl}}/users

###
GET  {{remoteUrl}}/cabins


###
GET  {{remoteUrl}}/orders

###
POST  {{remoteUrl}}/orders
Content-Type: application/json

{"service": "Städning","stugID": "61642c8556197124fffb29d3", "Date": "2022-01-06"}

###
PUT {{remoteUrl}}/orders/5
Content-Type: application/json

{"service": "sotning", "date": "2020-01-02"}


###
DELETE {{remoteUrl}}/orders/4
Content-Type: application/json

###
GET  {{remoteUrl}}/services

###
POST  {{remoteUrl}}/services
Content-Type: application/json

{"service": "stugmålning"}

###
PUT {{remoteUrl}}/services/9
Content-Type: application/json

{"service": "Måla stuga"}

###
DELETE {{remoteUrl}}/services/8
Content-Type: application/json




