@remoteUrl = https://secret-shelf-13108.herokuapp.com

@localUrl = http://127.0.0.1:5000


GET  {{remoteUrl}}/users

###
GET  {{remoteUrl}}/cabins


###
GET  {{remoteUrl}}/orders

###
POST  {{remoteUrl}}/orders
Content-Type: application/json

{"service": "sotning","stugID": "61642873e2d92ae2c0ff5e17", "Date": "2022-01-02"}

###
PUT {{remoteUrl}}/orders/5
Content-Type: application/json

{"service": "sotning", "date": "2020-01-02"}


###
DELETE {{remoteUrl}}/orders/7
Content-Type: application/json

###
GET  {{remoteUrl}}/services

###
POST  {{remoteUrl}}/services
Content-Type: application/json

{"service": "bastu tvätt"}

###
PUT {{remoteUrl}}/services/7
Content-Type: application/json

{"service": "Bastutvätt"}

###
DELETE {{remoteUrl}}/services/6
Content-Type: application/json



